### ISSUE TITLE
Chapter nesting use of parent selector

### ISSUE THREAD

**Issue by dannycobussen** [DigitPaint/css#2]
The nesting chapter (https://github.com/DigitPaint/scss-style-guide#nesting) says 
`Don't mix properties and selectors in a nesting level. Use & instead.`

But I've never seen someone doing it like this and I think in our situation the "bad" example is our good example.

**Comment by edwinvdgraaf** [comment]
What do you suggest?
Any cons or pros?

**Comment by hkrutzer** [comment]
I think we should drop that example entirely as nobody writes code like that and I see no advantages in doing it that way

**Comment by flurin** [comment]
Agreed. RM -rf
